-- popup: 팝업 1건 = 1행. PopupEntity(feature/popup/dataaccess/entity/PopupEntity.kt) 기준으로 다시 만든 DDL (2026-10-03, #28).
--
-- 확인 필요(엔티티만으로 확정할 수 없음, Supabase 실제 스키마와 대조할 것)
--   - popup_id 생성 방식: 엔티티는 IDENTITY. 실제가 bigserial 인지 GENERATED ... AS IDENTITY 인지 모름.
--   - UNIQUE (source, external_id): 코드가 전제하는 알려진 제약. 이름(popup_source_external_id_key)은 추정.
--   - view_count DEFAULT 0: 알려진 제약. 엔티티는 INSERT 에서 이 컬럼을 빼므로 DEFAULT 가 반드시 있어야 한다.
--   - FK interest_category_id → interest_category, area_id → favorite_area: 주석상 FK 로 쓰지만 실제 제약 유무 · ON DELETE 동작 모름.
--   - CHECK (source · reservation_type · place_resolution 값 목록): Hibernate 가 enum 으로 생성하는 제약. 실제 DB 에 있는지 모름.
--   - 인덱스: 엔티티에 선언이 없다. 실제 DB 의 인덱스(예: end_date, enriched_at, 좌표) 확인 필요.
--   - created_at · last_modified_at 의 DEFAULT: 엔티티(BaseEntity · JPA Auditing)가 채우므로 DB DEFAULT 유무는 모름.
--
-- #28 추가 컬럼(운영 DB 에는 아래 ALTER 로 적용)
--   ALTER TABLE popup ADD COLUMN last_seen_at timestamptz;
--   ALTER TABLE popup ADD COLUMN image_checked_at timestamptz;

CREATE TABLE popup (
    popup_id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 최초 생성 원천(KAKAO_MAP · PERPLEXITY)
    source               varchar(255)  NOT NULL,
    -- 원천 측 식별자. 카카오는 place id, Perplexity 는 NULL
    external_id          varchar(255),
    -- 정보 근거 URL 목록(병합 시 합집합)
    source_urls          text[],
    -- 마지막으로 받은 원천 응답 원문
    raw_payload          jsonb,
    title                varchar(500)  NOT NULL,
    brand                varchar(500),
    interest_category_id integer,
    area_id              integer,
    description          text,
    tags                 text[],
    -- 대표 이미지 URL 목록(image 단계가 채운다. URL 만 저장)
    image_urls           text[],
    -- 마지막 이미지 수집 시도 시각(못 찾은 경우에도 갱신)
    image_checked_at     timestamptz,
    start_date           date,
    end_date             date,
    opening_hours        text,
    -- NONE · RESERVATION · WAITING · BOTH · UNKNOWN
    reservation_type     varchar(255)  NOT NULL,
    reservation_url      varchar(2000),
    reservation_open_at  timestamptz,
    entry_fee            integer,
    place_id             varchar(255),
    place_name           varchar(255),
    address_road         varchar(255),
    address_jibun        varchar(255),
    latitude             double precision,
    longitude            double precision,
    -- EXACT · VENUE · UNRESOLVED
    place_resolution     varchar(255),
    enrich_retry_count   integer       NOT NULL,
    enriched_at          timestamptz,
    -- 카카오 키워드 검색에서 마지막으로 발견된 시각(기록만 한다)
    last_seen_at         timestamptz,
    view_count           bigint        NOT NULL DEFAULT 0,
    created_at           timestamp(6)  NOT NULL,
    last_modified_at     timestamp(6)  NOT NULL,

    CONSTRAINT popup_source_external_id_key UNIQUE (source, external_id),
    CONSTRAINT popup_source_check CHECK (source IN ('KAKAO_MAP', 'PERPLEXITY')),
    CONSTRAINT popup_reservation_type_check CHECK (reservation_type IN ('NONE', 'RESERVATION', 'WAITING', 'BOTH', 'UNKNOWN')),
    CONSTRAINT popup_place_resolution_check CHECK (place_resolution IN ('EXACT', 'VENUE', 'UNRESOLVED'))
);
