-- search_keyword: 수집 원천별 검색어. SearchKeywordEntity(feature/popup/dataaccess/entity/SearchKeywordEntity.kt) 기준 DDL (2026-10-03, #28).
--
-- 확인 필요(엔티티만으로 확정할 수 없음, Supabase 실제 스키마와 대조할 것)
--   - search_keyword_id 생성 방식: 엔티티는 IDENTITY. bigserial 인지 GENERATED ... AS IDENTITY 인지 모름.
--   - UNIQUE (target_source, keyword) · CHECK (target_source IN ('KAKAO_MAP','PERPLEXITY')): 알려진 제약. 제약 이름은 추정.
--   - is_active DEFAULT true 유무: 엔티티 기본값은 true 지만 DB DEFAULT 는 모름.
--   - 인덱스 · created_at / last_modified_at DEFAULT 유무.

CREATE TABLE search_keyword (
    search_keyword_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 원천에 그대로 넘기는 완성 검색어
    keyword           varchar(100) NOT NULL,
    -- KAKAO_MAP · PERPLEXITY
    target_source     varchar(20)  NOT NULL,
    -- false 면 탐색 배치에서 제외
    is_active         boolean      NOT NULL,
    created_at        timestamp(6) NOT NULL,
    last_modified_at  timestamp(6) NOT NULL,

    CONSTRAINT search_keyword_target_source_keyword_key UNIQUE (target_source, keyword),
    CONSTRAINT search_keyword_target_source_check CHECK (target_source IN ('KAKAO_MAP', 'PERPLEXITY'))
);
