services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      TZ: Asia/Seoul
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - certbot
    networks:
      - poppick

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: >
      /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - poppick
    volumes:
      - redis-data:/data

  spring_blue:
    image: eazy123/pop-pick:latest
    container_name: spring_blue
    restart: on-failure:3
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Seoul
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
    networks:
      - poppick
    volumes:
      - ./:/app/local
      - /var/log/poppick-log:/var/log/poppick-log
    depends_on:
      - redis

  spring_green:
    image: eazy123/pop-pick:latest
    container_name: spring_green
    restart: on-failure:3
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Seoul
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
    networks:
      - poppick
    volumes:
      - ./:/app/local
      - /var/log/poppick-log:/var/log/poppick-log
    depends_on:
      - redis

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail-config.prod.yml:/etc/promtail/config.yml
      - /var/log/poppick-log:/var/log/app
      - /var/lib/promtail:/var/lib/promtail
    command: -config.file=/etc/promtail/config.yml
    networks:
      - poppick

networks:
  poppick:
    driver: bridge

volumes:
  redis-data: