spring:
  config:
    activate:
      on-profile: local
    import: aws-secretsmanager:local/poppick

  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: validate

kakao:
  api-key: ${KAKAO_API_KEY}

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}

jwt:
  secret-key: ${JWT_SECRET_KEY}