spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

kakao:
  api-key: ${KAKAO_API_KEY}

google:
  client-id: ${GOOGLE_CLINET_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}

jwt:
  secret-key: ${JWT_SECRET_KEY}