spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  application:
    name: poppick

  profiles:
    active: local

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  ai:
    openai:
      embedding:
        model: text-embedding-3-small
      chat:
        model: gpt-5.6-terra
      api-key: ${OPENAI_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
